In [1]:
import pandas as pd
import numpy as np

In [5]:
#Sample Data

data = {
    'campaign_id': np.arange(1,11),
    'campaign_name': [f'Campaign {i}' for i in range(1,11)],
    'channel': ['Email', 'Social Media', 'PPC', 'Email', 'PPC', 'Social Media', 'Email', 'PPC', 'Social Media', 'Email'],
    'date': pd.date_range(start='2023-01-01', periods=10, freq='M'),
    'spend': np.random.uniform(1000, 5000, 10),
    'visitors': np.random.randint(1000, 5000, 10),
    'conversions': np.random.randint(50, 500, 10),
    'revenue': np.random.uniform(10000, 50000, 10) 
}

df = pd.DataFrame(data)
df.to_csv('C:\\Users\\ALAMEEN\\marketing_campaign_data.csv', index=False)
df.head()

C:\Users\ALAMEEN\AppData\Local\Temp\ipykernel_18704\1354387169.py:7: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  'date': pd.date_range(start='2023-01-01', periods=10, freq='M'),

,campaign_id,campaign_name,channel,date,spend,visitors,conversions,revenue
0,1,Campaign 1,Email,2023-01-31,3866.761528,1726,228,11297.776143
1,2,Campaign 2,Social Media,2023-02-28,1272.181286,3568,241,12842.438895
2,3,Campaign 3,PPC,2023-03-31,1430.039019,4441,424,35455.809848
3,4,Campaign 4,Email,2023-04-30,4584.591539,4677,183,39855.631531
4,5,Campaign 5,PPC,2023-05-31,2475.052164,2721,73,10269.447263

In [7]:
df = pd.read_csv('C:\\Users\\ALAMEEN\\marketing_campaign_data.csv')

In [9]:
#Summary Statistics

df.describe()

       campaign_id        spend     visitors  conversions       revenue
count     10.00000    10.000000    10.000000    10.000000     10.000000
mean       5.50000  2576.859135  3035.800000   252.500000  27521.254674
std        3.02765  1243.693449  1140.081069   125.791936  14962.667196
min        1.00000  1272.181286  1592.000000    73.000000  10269.447263
25%        3.25000  1692.838858  2016.500000   186.500000  13306.797906
50%        5.50000  2177.647019  3063.000000   234.500000  27549.638217
75%        7.75000  3518.834187  3893.500000   322.750000  38755.676110
max       10.00000  4584.591539  4677.000000   461.000000  49714.138710

In [10]:
#To check for missing values

df.isnull().sum()

campaign_id      0
campaign_name    0
channel          0
date             0
spend            0
visitors         0
conversions      0
revenue          0
dtype: int64

In [12]:
#Campaign Analysis

#Calculating key metrics for each campaign

#1. Conversion Rate
df['conversion_rate'] = df['conversions'] / df['visitors']
df['conversion_rate']

0    0.132097
1    0.067545
2    0.095474
3    0.039128
4    0.026828
5    0.100147
6    0.115192
7    0.168342
8    0.085429
9    0.056771
Name: conversion_rate, dtype: float64

In [14]:
# Cost per Conversion
df['cost_per_conversion'] = df['spend'] / df['conversions']
df['cost_per_conversion']

0    16.959480
1     5.278761
2     3.372734
3    25.052413
4    33.904824
5     7.007910
6     3.728926
7     7.334316
8     8.548766
9    40.197524
Name: cost_per_conversion, dtype: float64

In [16]:
# Return on Investment
df['roi'] = (df['revenue'] - df['spend']) / df['spend']
df['roi']

0     1.921767
1     9.094818
2    23.793596
3     7.693388
4     3.149184
5    19.803530
6     7.551237
7    22.391447
8    13.218734
9     6.110167
Name: roi, dtype: float64

In [17]:
# Customer Acquisition Cost
df['cac'] = df['spend'] / df['conversions']
df['cac']

0    16.959480
1     5.278761
2     3.372734
3    25.052413
4    33.904824
5     7.007910
6     3.728926
7     7.334316
8     8.548766
9    40.197524
Name: cac, dtype: float64

In [19]:
df.head(10)

,campaign_id,campaign_name,channel,date,spend,visitors,conversions,revenue,conversion_rate,cost_per_conversion,roi,cac
0,1,Campaign 1,Email,2023-01-31,3866.761528,1726,228,11297.776143,0.132097,16.959480,1.921767,16.959480
1,2,Campaign 2,Social Media,2023-02-28,1272.181286,3568,241,12842.438895,0.067545,5.278761,9.094818,5.278761
2,3,Campaign 3,PPC,2023-03-31,1430.039019,4441,424,35455.809848,0.095474,3.372734,23.793596,3.372734
3,4,Campaign 4,Email,2023-04-30,4584.591539,4677,183,39855.631531,0.039128,25.052413,7.693388,25.052413
4,5,Campaign 5,PPC,2023-05-31,2475.052164,2721,73,10269.447263,0.026828,33.904824,3.149184,33.904824
5,6,Campaign 6,Social Media,2023-06-30,2389.697288,3405,341,49714.138710,0.100147,7.007910,19.803530,7.007910
6,7,Campaign 7,Email,2023-07-31,1719.034834,4002,461,14699.874938,0.115192,3.728926,7.551237,3.728926
7,8,Campaign 8,PPC,2023-08-31,1965.596749,1592,268,45978.152973,0.168342,7.334316,22.391447,7.334316
8,9,Campaign 9,Social Media,2023-09-30,1684.106866,2306,197,23945.866943,0.085429,8.548766,13.218734,8.548766
9,10,Campaign 10,Email,2023-10-31,4381.530081,1920,109,31153.409491,0.056771,40.197524,6.110167,40.197524